---
title: "ESMV UE5"
output: html_document
date: "2026-04-13"
---

```{r}
rm(list = ls())

library(rstudioapi)
library(tidyverse)

Sys.unsetenv("VIRTUAL_ENV")
library(reticulate)
py_require("MIDIUtil")
py_require("mido")
py_require("pandas")
py_require("music21")
py_require("partitura")
py_require("setuptools")
py_require("typing-extensions")
py_config()
py_require()

setwd(dirname(getActiveDocumentContext()$path))  
```


## music21 Grundlagen
Online-Referenz aller Module von music21:
https://music21.org/music21docs/moduleReference/index.html

```{python}
#Importieren aller Module
from music21 import * 

#Konfigurieren von music21
#[1] - No - No - Yes
configure.run()
```

# Präsentation der Übung
```{r}
n <-4 
sample(n, n, replace = FALSE)
```


# Kopien und Verweise in music21/Python
.append() erzeugt keine Kopie, sondern fügt die selbe Note an verschiedenen Stellen ein.
```{python}

n = note.Note("C4")

m1 = stream.Measure(number=1)
m2 = stream.Measure(number=2)

m1.append(n)
m1.append(n)
m2.append(n)

p = stream.Part()
p.append(m1)
p.append(m2)

n.pitch.name = "A"

p.show()

```

# for-Schleifen, automatisiertes Bearbeiten von Streams
```{python}

#Durchlaufen von Listen in Python
our_list = ["Bb", "Db", "Fb"]
nbr_list = [1, 2]

for i in our_list:
  print(i)

#Erzeugen einer Liste mit range()
for i in range(1,10):
  print(i)

#Durchlaufen einer Teilmenge einer Liste
for i in our_list[2:]:
  print(i)

for i in range(1,10)[3:7]:
  print(i)

for i in our_list:
  for j in range(1,3):
    print(i,j)

```

#for-Schleifen / recurse & flatten in music21
```{python}
score = corpus.parse("bach/bwv65.2.xml")

#verschachtelte for-Schleifen um music21 Streams zu durchlaufen
#kompliziert und unpraktisch
for p in score.parts:
  for m in p:
    print(m)

score.show()

#recurse() und flatten() konvertiert den Stream von einer Baumstruktur in eine Liste

#recurse() ist eine Tiefensuche, Streams (z.B. Measures) bleiben erhalten
#über die eckigen Klammern [:50], können wir nur eine Teilmenge durchlaufen, in diesem Fall die ersten 50 Elemente im Stream

for i in score.recurse()[:50]:
  print(i)

#flatten() ist eine Breitensuche, Streams (z.B. Measures) werden aufgelöst 
for i in score.flatten()[:50]:
  print(i)
 
#Es kann ein einfacher Filter hinzugefügt werden, um nur Noten (.notes) oder nur Noten und Pausen (.notesAndRests) zu bekommen.
for i in score.flatten().notes:
  print(i)
  
for i in score.recurse().notesAndRests:
  print(i)
  
#### Erste einfache Analysen ####

#Anzahl der Noten in einer Partitur zählen
count = 0  
for i in score.recurse().notes:
  count = count + 1

#Alternativ können wir den mit recurse() reduzierten und .notes gefilterten Stream in einer Liste speichern.
#Über die Länge der Liste (= Anzahl der Elemente in der Liste) kann die Anzahl an Noten bestimmt werden.
noten = list(score.recurse().notes)
len(noten) 
  
#Analyse der Anzahl an TimeSignature Changes
#mit der Funktion isinstance() können Sie überprüfen ob ein Objekt im Stream einen gewissen Typ hat, z.B. meter.TimeSignature oder note.Note
count = 0
for i in score.recurse():
  if isinstance(i, meter.TimeSignature):
    count = count + 1
    
count_p = 0
for i in score.recurse():
  if isinstance(i, stream.Part):
    count_p = count_p + 1

#Genaue eine TimeSignature für jede Stimme, also keine Wechsel. 
count - count_p 
```